[package]
name = "FlowPay"
version = "1.0.0"
authors = ["FlowPay Team"]

[addresses]
flowpay = "0x06ed61974ad9b10aa57c7ed03c7f6936797caf4b62fd5cc61985b4f592f80693"
merkle_trade = "0x1" # Replace with actual Merkle Trade testnet address
hyperion = "0x2" # Replace with actual Hyperion testnet address

[dev-addresses]
flowpay = "0x06ed61974ad9b10aa57c7ed03c7f6936797caf4b62fd5cc61985b4f592f80693"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]